-- MySQL Script generated by MySQL Workbench
-- Sat Oct 21 16:58:43 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`users` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(50) NOT NULL,
  `email` VARCHAR(200) NOT NULL,
  `password` MEDIUMTEXT NOT NULL,
  `user_img` MEDIUMBLOB NOT NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `user_id_UNIQUE` ON `mydb`.`users` (`user_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`matches`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`matches` (
  `match_id` INT NOT NULL AUTO_INCREMENT,
  `title` MEDIUMTEXT NOT NULL,
  `match_capacity` INT NOT NULL,
  `is_private` TINYINT NOT NULL,
  `password` MEDIUMTEXT NULL,
  `has_started` TINYINT NOT NULL,
  PRIMARY KEY (`match_id`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `match_id_UNIQUE` ON `mydb`.`matches` (`match_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`users_matches`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`users_matches` (
  `user_id` INT NOT NULL,
  `match_id` INT NOT NULL,
  PRIMARY KEY (`user_id`, `match_id`),
  CONSTRAINT `user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `match_id`
    FOREIGN KEY (`match_id`)
    REFERENCES `mydb`.`matches` (`match_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `match_id_idx` ON `mydb`.`users_matches` (`match_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`chat_message`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`chat_message` (
  `message_id` INT NOT NULL AUTO_INCREMENT,
  `match_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `message_text` MEDIUMTEXT NOT NULL,
  `timestamp` DATETIME NOT NULL,
  PRIMARY KEY (`message_id`),
  CONSTRAINT `match_id`
    FOREIGN KEY (`match_id`)
    REFERENCES `mydb`.`matches` (`match_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `match_id_idx` ON `mydb`.`chat_message` (`match_id` ASC) VISIBLE;

CREATE INDEX `user_id_idx` ON `mydb`.`chat_message` (`user_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`match_state`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`match_state` (
  `match_id` INT NOT NULL,
  `current_player` INT NOT NULL,
  `current_card_color` VARCHAR(45) NOT NULL,
  `current_card_number` VARCHAR(45) NOT NULL,
  `remaining_cards` JSON NOT NULL,
  CONSTRAINT `match_id`
    FOREIGN KEY (`match_id`)
    REFERENCES `mydb`.`matches` (`match_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `current_player`
    FOREIGN KEY ()
    REFERENCES `mydb`.`users` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `match_id_idx` ON `mydb`.`match_state` (`match_id` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
